# Set of common Operating System processes to be excluded
OS = {
    # Windows
    "system",
    "system idle process",
    "smss.exe",
    "csrss.exe",
    "wininit.exe",
    "winlogon.exe",
    "services.exe",
    "lsass.exe",
    "svchost.exe",
    "explorer.exe",
    "dwm.exe",
    "fontdrvhost.exe",
    "registry",
    "memcompression",
    "msmpeng.exe",
    "securityhealthservice.exe",
    "runtimebroker.exe",
    "System",
    "Registry",
    "System Idle Process"

    # Mac
    "kernel_task",
    "launchd",
    "syslogd",
    "notifyd",
    "configd",
    "distnoted",
    "windowserver",
    "dock",
    "finder",
    "sandboxd",
    "tccd",
    "cfprefsd",
    "powerd",
    "coreservicesd",
    "hidd",
    "ioregistryd",
}